name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.war"
          target: "/home/ec2-user/deploy-temp"
          strip_components: 1
          overwrite: true

      - name: Deploy to Tomcat
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /opt/tomcat/webapps/JAVA*
            sudo mv /home/ec2-user/deploy-temp/*.war /opt/tomcat/webapps/JAVA.war

            # restart tomcat (depends on your setup)
            sudo systemctl restart tomcat || sudo /opt/tomcat/bin/shutdown.sh && sudo /opt/tomcat/bin/startup.sh
